select createDate
      ,settleDate
      ,TradingDay
      ,SecuCode
      ,ClosePrice
      ,OpenPrice
      ,HighPrice
      ,LowPrice
      ,ExeClosePrice
      ,ExeOpenPrice
      ,ExeHighPrice
      ,ExeLowPrice
      ,NonRestrictedShares
      ,AFloats
      ,TotalShares
      ,TurnoverVolume
      ,NonRestrictedCap
      ,AFloatsCap
      ,TotalCap
      ,SecuAbbr
      ,IndustrySecuCode_I
      ,FirstIndustryName
      ,IndustrySecuCode_II
      ,SecondIndustryName
      ,PE
      ,PB
      ,PS
      ,PCF
      ,DividendYield
      ,DividendRatio
      ,TTMIncome
      ,EndDate
      ,MaxEfctInfoPublDate
      ,GP_Margin
      ,NP_Margin
      ,ROA
      ,ROE
      ,AssetsTurnover
      ,EquityTurnover
      ,Cash_to_Assets
      ,Liability_to_Assets
      ,EquityMultiplier
      ,CurrentRatio
      ,Income_Growth_YOY_Comparable
      ,NPPC_Growth_YOY_Comparable
      ,GP_Margin_Comparable
      ,GP_Margin_Growth_YOY_Comparable
      ,NP_Margin_Comparable
      ,NP_Margin_Growth_YOY_Comparable
      ,Income_Growth_Pre_Comparable
      ,NPPC_Growth_Pre_Comparable
      ,GP_Margin_Growth_Pre_Comparable
      ,NP_Margin_Growth_Pre_Comparable
      ,NPPC_Growth_Pre_Season
      ,NPPC_Growth_YOY_Season
      ,NPLNRP_Growth_Pre_Season
      ,NPLNRP_Growth_YOY_Season
      ,Income_Growth_Pre_Season
      ,Income_Growth_YOY_Season
      ,Income_Growth_Qtr_Comparable
      ,NPPC_Growth_Qtr_Comparable
      ,GP_Margin_Qtr
      ,GP_Margin_Growth_Qtr_Comparable
      ,IPS_Qtr
      ,EPS_Qtr
      ,ROE_Qtr
      ,Income_Growth_Pre
      ,NPPC_Growth_Pre
      ,NPLNRP_Growth_Pre
      ,GP_Margin_Growth_Pre
      ,NP_Margin_Growth_Pre
      ,Income_Growth_YOY
      ,NPPC_Growth_YOY
      ,NPLNRP_Growth_YOY
      ,GP_Margin_Growth_YOY
      ,NP_Margin_Growth_YOY
      ,IPS
      ,EPS
      ,CFPS
      ,Pre_IPS
      ,Pre_EPS
      ,Pre_CFPS
      ,YOY_IPS
      ,YOY_EPS
      ,YOY_CFPS
      ,rPE
      ,rPB
      ,rPS
      ,rPCF
      ,CFPS_Growth_Pre
      ,CFPS_Growth_YOY
      ,CashNetAssets_Growth_Pre
      ,CashNetAssets_Growth_YOY
      ,SalesCashRatio
      ,ShortTermSolvency
      ,LongTermCashRepaymentAbility
      ,CashCreationAbility
      ,NetCashPSI
      ,Pre_NetCashPSI
      ,YOY_NetCashPSI
      ,NetCashInv_Growth_Pre
      ,NetCashInv_Growth_YOY
      ,CashPSI
      ,Pre_CashPSI
      ,YOY_CashPSI
      ,CashPSF
      ,Pre_CashPSF
      ,YOY_CashPSF
      ,CashFinancial_Growth_Pre
      ,CashFinancial_Growth_YOY
      ,EBITDAPS
      ,Pre_EBITDAPS
      ,YOY_EBITDAPS
      ,EBITDAPS_Growth_Pre
      ,EBITDAPS_Growth_YOY
      ,GoodWill_to_NetAsset
      ,ReceivableTurnover
      ,InventoryTurnover
      ,DPS
      ,DPS_Growth_Pre
      ,DPS_Growth_YOY
      ,DividendYield_Growth_Pre
      ,DividendYield_Growth_YOY
      ,DividendRatio_Growth_Pre
      ,DividendRatio_Growth_YOY
      ,SettlePrice
      ,IndusInnerCode
      ,IndusCreatePrice
      ,IndusSettlePrice
      ,ExecutivesProp
      ,InstitutionNum
      ,InstitutionProp
      ,RegionScore
      ,ExeClosePrice_CreateDate_Wind
      ,ExeClosePrice_SettleDate_Wind
      ,Momentum20Day
      ,Momentum40Day
      ,Momentum60Day
      ,Momentum120Day
      ,Momentum180Day
      ,Momentum240Day
      ,PriceDiff
      ,DayDiff
      ,TurnoverRatio
      ,AvgTurnoverPrice
      ,AvgTurnoverPriceFactor
      ,AvgTurnoverRatio5Day
      ,AvgTurnoverRatio10Day
      ,AvgTurnoverRatio20Day
      ,AvgTurnoverRatio40Day
      ,AvgTurnoverRatio60Day
      ,AvgTurnoverRatio120Day
      ,E_EPS
      ,E_growth
      ,FreeFloat_Total
      ,EPS_CFPS
      ,AvgTurnoverValue
	  ,AvgTurnoverValue5Day	
	  ,AvgTurnoverValue10Day	
	  ,AvgTurnoverValue20Day	
	  ,AvgTurnoverValue40Day	
	  ,AvgTurnoverValue60Day	
	  ,AvgTurnoverValue120Day	
	  ,Std20Day				
	  ,Std60Day				
	  ,Std120Day				
	  ,Std240Day				
	  ,Beta20Day				
	  ,Beta60Day				
	  ,Beta120Day				
	  ,Beta240Day				
from winddb.dbo.FactorMonthly_Comparable
where TradingDay='{0}'
order by SecuCode



